### ISSUE TITLE
Logout users due to LS update (ls migration)

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#128]
With the introduction of the UIDW Key, users who were logged in before are not able to properly use the UIDW as they don't have a UIDW key in ls.

**Comment by samosaboy** [comment]
Fixed in 5a98eb0f28a04bf4af85ff2a24244b8fda9875eb

Users coming onto the site again will have to log in, as there is a timestamp check in place. If the timestamp is equal to a certain value, it will log them out immediately. Once they re-log in, the timestamp will update and next time they come on they won't have to re-log.
