### ISSUE TITLE
Add a "Tip Button" for Posts

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#228]
This button only need be a "$" sign. When clicked, a dialog should prompt the user asking them how much they would like to tip and in what currency. It should provide the same overview as the Unified ID wallet's transfer (i.e. tx fee, etc). After clicking "OK" it should provide the same breakdown and require confirmation as is the same in #218

**Comment by samosaboy** [comment]
![Screen Shot 2020-04-25 at 4 35 15 PM](https://user-images.githubusercontent.com/16053325/80290401-c3102e00-8712-11ea-9202-8642834aec27.png)

Added a tipping popup instead that lets a user quickly create a tip. Should we still show fees and stuff in this tiny popup? Seems unnecessary because when you click "Post" you'll see the normal tipping confirmation visuals (#218)
