### ISSUE TITLE
UI for displaying ATMOS staking / earning ATMOS

### ISSUE THREAD

**Issue by bluabaleno** [Novusphere/discussions-app#270]
<img width="1552" alt="Screen Shot 2020-03-17 at 12 48 47 PM" src="https://user-images.githubusercontent.com/14120416/76858122-b6183900-684e-11ea-85d7-fe9b2f304fdf.png">
or
<img width="1552" alt="Screen Shot 2020-03-17 at 12 53 38 PM" src="https://user-images.githubusercontent.com/14120416/76858133-ba445680-684e-11ea-86e5-979ba0bab55e.png">

We should also make tokens symbols in the wallet page /balance drop-down to be linked to the respective tag, i.e clicking on ATMOS token symbol will take you to #atmos

**Comment by Novusphere** [comment]
Since total generated is not easy at this time to implement, I would suggest changing this to "Earning ~123.567 ATMOS/day"

Regarding how to calculate this, first determine the total ATMOS in the system, for example the below:

```js
            const chains = await rpc.get_table_rows({
                json: true,
                code: 'nsuidcntract',
                scope: 'nsuidcntract',
                table: 'stats',
                limit: 100,
            });

            chains.rows.forEach(e => {
                console.log(`${e.chain_id} ${e.token_contract}::${e.symbol.split(',')[1]} ${e.supply}`);
            });
```

yields
```
0 novusphereio::ATMOS 1638001.190 ATMOS
1 eosio.token::EOS 22.0986 EOS
2 boidcomtoken::BOID 33150.1599 BOID
3 metpacktoken::MPT 7000.0000 MPT
4 pumlhealthio::PUML 100.0000 PUML
5 blockbasetkn::BBT 500.2000 BBT
```

Once you know the total ATMOS in the system the calculation for daily estimate is `(userAmount / totalAmount) * 2740`
