### ISSUE TITLE
Error loading site?

### ISSUE THREAD

**Issue by Novusphere** [Novusphere/discussions-app#60]
https://media.discordapp.net/attachments/584804633986203696/646018432877199390/photo_2019-11-18_16-05-36.jpg?width=927&height=695

Seems this was on visiting the site for some user

**Comment by samosaboy** [comment]
I think the error might be caused by persisting the statusJSON object inside LS causing the error

```
    @persist('object')
    @observable statusJson = {
        bk: null,
        scatter: null,
    }
```

Both ` bk` and `scatter` have a post key value which is their post public key. I added a check for hasAccount which is computed if those one of those two values exist, perhaps it might solve it? bdc80eb5a3f39bed89b78956e5d9eb6236c81475

**Comment by samosaboy** [comment]
Seems to be resolved as the user did not experience this issue.
